app: reyc-app-api
service: reyc-app-api
frameworkVersion: '3'

# Provider
provider:
  name: aws
  runtime: nodejs18.x
  region: ${self:custom.common.resourcesRegion}
  stage: dev
  logRetentionInDays: 7
  lambdaHashingVersion: 20201221
  versionFunctions: false
  memorySize: ${self:custom.common.memSize.${self:custom.common.stage}}
  environment:
    # COGNITO ENVIRONMENT VARIABLES
    COGNITO_USER_POOL_ID: ${cf:reyc-app-cognito-${self:custom.common.stage}.ReycAppUserPoolId}
    COGNITO_USER_POOL_ARN: ${cf:reyc-app-cognito-${self:custom.common.stage}.ReycAppCognitoUserPoolArn}
    COGNITO_CLIENT_ID: ${cf:reyc-app-cognito-${self:custom.common.stage}.ReycAppPoolClientId}
    # S3 ENVIRONMENT VARIABLES
    S3_UPLOAD_BUCKET_1: ${cf:reyc-app-bgprocess-${self:custom.common.stage}.ReycAppS3BucketName}
  iam:
    role:
      statements:
        # COGNITO PERMISSIONS
        - Effect: "Allow"
          Action:
            - "cognito-idp:AdminConfirmSignUp"
            - "cognito-idp:ListUsers"
            - "cognito-idp:InitiateAuth"
            - "cognito-idp:RespondToAuthChallenge"
            - "cognito-idp:AdminInitiateAuth"
            - "cognito-idp:AdminCreateUser"
            - "cognito-idp:AdminSetUserPassword"
          Resource: "*"
        # S3 PERMISSIONS
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource: "*"

functions:
  - ${file(./functions-test.yml)}
  - ${file(./functions-auth.yml)}
  - ${file(./functions-storage.yml)}
  - ${file(./functions-bgprocess.yml)}

custom:
  common: ${file(../../serverless.common.yml):custom}